# Generated by Django 5.0.3 on 2024-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name: ')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email: ')),
                ('comment', models.TextField(verbose_name='Comment: ')),
            ],
        ),
    ]
