# Generated by Django 5.0.3 on 2024-05-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review_main_review_created_9196a5_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(null=True),
        ),
    ]
