# Generated by Django 5.0.3 on 2024-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_image_remove_product_image_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=70)),
                ('title2', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
